language: node_js
node_js:
  - node

install:
  - npm install newman

before_script:
  - node --version
  - npm --version
  - node_modules/.bin/newman --version

script:
  - node_modules/.bin/newman run 2019/Hack\ Oregon\ Housing\ 2019\ API.postman_collection.json
