language: node_js
node_js:
  - node

install:
  - npm install newman
  - npm install newman-reporter-slack

before_script:
  - node --version
  - npm --version
  - node_modules/.bin/newman --version

script:
  - ./scripts/run.sh
